### ISSUE TITLE
Dispatcher trampoline should preserve contents of VFP registers

### ISSUE THREAD

**Issue by alirazeen** [beehive-lab/mambo#2]
If VFP registers are present, the dispatcher trampoline should preserve their contents. Otherwise, correctness of execution may not be guaranteed. Consider the following excerpt taken from the objdump output of libjpeg for Android 4.1.1:

```asm
   14784:       f2c01012        vmov.i32        d17, #2 ; 0x00000002
   14788:       eddd2b02        vldr    d18, [sp, #8]
   1478c:       ee800b90        vdup.32 d16, r0
   14790:       e088210e        add     r2, r8, lr, lsl #2
   14794:       13a03000        movne   r3, #0
  
   14798:       1a000013        bne     147ec <jinit_d_coef_controller+0x3bc>

   1479c:       f26248a1        vadd.i32        d20, d18, d17
   147a0:       e3a03004        mov     r3, #4
   147a4:       f3c03010        vmov.i32        d19, #128       ; 0x00000080
   147a8:       f5d2f0b8        pld     [r2, #184]      ; 0xb8
   147ac:       f26458a1        vadd.i32        d21, d20, d17
   147b0:       e2822020        add     r2, r2, #32
   147b4:       f26071b0        vorr    d23, d16, d16
```

In this example, the basic block at the beginning sets a value in d16 at `1478c`. If the branch at `14798` is not taken, the dispatcher starts at the target address of `1479c` and scans for the next basic block. During this process, the instructions generated by gcc for mambo may make use of VFP registers for scratch space. For example, in my compiled version of mambo, I see register `d16` being used in `hash_add`, `mambo_memcpy`, and other places. As a result, the values of the VFP registers may be clobbered by mambo when execution resumes at the basic block for `1479c`. This causes problems later on in the execution. In my case, I eventually get a segfault.

The fix that I have locally is simple:

```diff
diff --git a/dbm.c b/dbm.c
index 503be38..f687908 100644
--- a/dbm.c
+++ b/dbm.c
@@ -304,11 +304,11 @@ void init_thread(dbm_thread *thread_data) {
   memcpy(&thread_data->code_cache->blocks[0], (uint8_t *)dispatcher_trampoline-4, sizeof(dbm_block)*2);
   dispatcher_thread_data = (dbm_thread **)((uint32_t)&thread_data->code_cache->blocks[0] + global_data.disp_thread_data_off);
   *dispatcher_thread_data = thread_data;
-  thread_data->code_cache->blocks[0].words[20] = (uint32_t)thread_data->scratch_regs;
+  thread_data->code_cache->blocks[0].words[24] = (uint32_t)thread_data->scratch_regs;
   debug("*thread_data in dispatcher at: %p\n", dispatcher_thread_data);

 #ifdef DBM_TRACES
-  write_p = (uint16_t *)&thread_data->code_cache->blocks[0].words[23];
+  write_p = (uint16_t *)&thread_data->code_cache->blocks[0].words[27];
   thread_data->trace_head_incr_addr = ((uint32_t)write_p) + 1 - 4;
   copy_to_reg_32bit(&write_p, r1, (uint32_t)thread_data->exec_count);

diff --git a/dispatcher.S b/dispatcher.S
index 3f11229..4a49f4d 100644
--- a/dispatcher.S
+++ b/dispatcher.S
@@ -42,6 +42,8 @@ dispatcher_trampoline:
   PUSH {R1}
   # R0 is target, R1 where to put address
   ADD R1, SP, #24
+  VPUSH {d0-d15}
+  VPUSH {d16-d31}
   LDR R3, disp_thread_data
   LDR R9, dispatcher_addr

@@ -56,6 +58,8 @@ dispatcher_trampoline:
   MSR CPSR, r1
   LDR R0, scratch_space
   LDM R0, {R0-R2}
+  VPOP {d16-d31}
+  VPOP {d0-d15}
   POP {r3, r4, r9, r12, lr, pc}
 ret_addr: .word 0
 dispatcher_addr: .word dispatcher
```

This will clearly not work in an ARM processor that does not have the VFP extensions implemented, or if it only implements VFPv2/VFPv2-D16 (so registers d16-d31 will not be present). This is why I am not submitting this as a pull request.

Please let me know if you had any questions. Thanks!

**Comment by lgeek** [comment]
The workaround I've been using is to build MAMBO without NEON/VFP support. It should also also be linked against a NEON/VFP-free stdlib implementation.

However, you are right that the proper solution is to preserve the value of the VFP registers (note to self, also the value of FPSCR). I'll look into how to support VFP versions with either 16 or 32 registers, but I'm not too fussed about supporting processors with no VFP because as far as I know it's implemented in all ARMv7-A cores.

**Comment by lgeek** [comment]
This was fully fixed by the patch from April 2017, however that assumes an implementation with 32 double precision FP registers. At the time I thought it might be useful to maintain compatibility with 16 FP register implementations by adding some sort of runtime detection. However, the NEON extension requires 32 FP registers and we're already building MAMBO assuming NEON is supported. Because the only ARMv7A processor without NEON support is Tegra2, we're not going to bother supporting implementations without NEON support or with only 16 FP registers.
